services:
  # Servicio de la aplicación Spring Boot
  app:
    image: mapamundi-app
    container_name: mapamundi-isidoronm
    ports:
      - "9080:8080"
    environment:
    depends_on:
      - db

  # Servicio de MySQL
  db:
	image: mysql:latest
	container_name: mysql_vdlp
	hostname: mysql.vdlp
	ports:
	  - "3306:3306"
	environment:
	  MYSQL_ROOT_PASSWORD: mysql_123
	  MYSQL_USER: isidoronm
	  MYSQL_PASSWORD: mm123
	  MYSQL_DATABASE: mapa_mundi
	volumes:
	  - ./mysql/conf.d:/etc/mysql/conf.d
	  - ./mysql/init:/docker-entrypoint-initdb.d # Los scripts que se dejen en ./mysql/init serán cargados automáticamente por el contenedor.
	  - mysql_data:/var/lib/mysql
	restart: always


# Volúmenes persistentes
volumes:
  mysql_data: